name: "Hello"

on:
  push:
    branches:
      - master  

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with: 
          gh-context: ${{ toJson(github) }}